---
title: "simulation on real data- linear outcome-MAGMA"
output: html_document
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = "/Users/nkui/Library/CloudStorage/OneDrive-InsideMDAnderson/MAGMA/output/continuous/")#, fig.width = 6, fig.height = 8)

library(dplyr)
setwd("/Users/nkui/Library/CloudStorage/OneDrive-InsideMDAnderson/MAGMA/")
df0.05<-get(load("magma_0.05c.Rdata"))
df0.2<-get(load("magma_0.2c.Rdata"))

ES_FIXED_SETS <- list(
  set0 = c(0, 0, 0, 0),
  set1 = c(0.1, 0.1, -0.1, -0.1),
  set2 = c(0.2, 0.2, -0.2, -0.2) # Adjusted from 0.25 in the previous algorithm
)
es1_values <- c(0.1, 0.2, 0.3, 0.4) # Causal SNP 1
es2_values <- c(-0.1, -0.2, -0.3, -0.4) # Causal SNP 2

NUM_FIXED_SETS <- length(ES_FIXED_SETS) # 3
NUM_ES1 <- length(es1_values)           # 4
NUM_ES2 <- length(es2_values)           # 4
# Block size for the outer 'fixed' set: 4 * 4 = 16
SCENARIOS_PER_SET <- NUM_ES1 * NUM_ES2 

# List of data frames to process
df_list <- list(df0.2 = df0.2, df0.05 = df0.05)
results_list <- list()

# --- 2. Loop for Parameter Matching and Transformation ---
for (name in names(df_list)) {
  # Get the current data frame
  df <- df_list[[name]]
  cat(paste0("Processing ", name, "...\n"))

  # FIX: Convert the 'job' column to numeric (retains the fix for the previous error)
  df$job <- suppressWarnings(as.numeric(as.character(df$job)))
  
  # Initialize only the required new columns
  df$es1 <- NA
  df$es2 <- NA
  df$es_other <- NA
  
  # Filter out any rows where job index might have become NA due to bad data
  df_clean <- df[!is.na(df$job), ] 

  # Loop through each 'job' index in the current data frame
  for (job_index in df_clean$job) {
    idx_rem <- job_index - 1  # zero-based

    # --- Simplified Parameter Matching Logic (No Beta0) ---
    
    # 1. Determine i_fixed (es_other)
    i_fixed <- floor(idx_rem / SCENARIOS_PER_SET) + 1
    current_fixed <- ES_FIXED_SETS[[i_fixed]]
    
    idx_rem <- idx_rem %% SCENARIOS_PER_SET

    # 2. Determine i_es1 (es1)
    i_es1 <- floor(idx_rem / NUM_ES2) + 1
    current_es1 <- es1_values[i_es1]
    
    idx_rem <- idx_rem %% NUM_ES2
    
    # 3. Determine i_es2 (es2)
    i_es2 <- idx_rem + 1
    current_es2 <- es2_values[i_es2]
    # --- End of Matching Logic ---

    # Assign values back to the corresponding row in the data frame
    df[df$job == job_index, "es1"] <- current_es1
    df[df$job == job_index, "es2"] <- current_es2
    df[df$job == job_index, "es_other"] <- current_fixed[1]
  }

  # --- 3. Final Renaming and Selection (Excluding Beta0 and unnecessary columns) ---
  df_final <- df %>%
    dplyr::rename(
      JobIndex = job,
      PowerSeparated = power_true,
      PowerCombined = power_mis
    ) %>%
    # Select only the required columns and order them
    dplyr::select(
      JobIndex, es_other, es1, es2, PowerSeparated, PowerCombined
    )
    
  # Store the final result in the results list
  results_list[[name]] <- df_final
}

# The results are now stored in results_list:
 df5 <- results_list[["df0.05"]]
 df6 <- results_list[["df0.2"]]


#------------------PLOT------------------------#
library(ggplot2)
library(cowplot)
library(gridExtra)
library(KATSP)
library(ggpubr)
library(grid)
es1<-c(0.1,0.2,0.3,0.4)
es2<-c(-0.1,-0.2,-0.3,-0.4)


theme_set(theme_cowplot())
mytheme = list(
  theme_classic()+
    theme(panel.background = element_blank(),strip.background = element_rect(colour=NA, fill=NA),panel.border = element_rect(fill = NA, color = "black"),
          legend.position="none", )
)

```

<!--## MAF=0.05, linear, other effect size=0-->

```{r fig5_0,echo=FALSE}
df <- df5[df5$es_other == 0,]

# power1 <- cbind(df[,c(2,3,5)],rep("Analytic,True",16))
# power2 <- cbind(df[,c(2,3,6)],rep("Analytic,Mis",16))
power3 <- cbind(df[,c(3,4,5)],rep("Sim,True",16))
power4 <- cbind(df[,c(3,4,6)],rep("Sim,Mis",16))

# colnames(power1)[3:4]<-c("power","group")
# colnames(power2)[3:4]<-c("power","group")
colnames(power3)[3:4]<-c("power","group")
colnames(power4)[3:4]<-c("power","group")

dfnew<-rbind(power3,power4)
dfsub<-list()
line_types <- c(  "dashed", "dashed")

plots <- list()

for (i in 1:4){
  dfsub[[i]] <- dfnew[dfnew$es2==es2[i], ]
  plots[[i]] <- ggplot(dfsub[[i]], aes(x = es1, y = power, group=group)) +
          geom_point(aes(color=group,shape=group)) +
          geom_line(aes(color=group,linetype=group)) +
          scale_linetype_manual(values = line_types) +
          labs(title = bquote(beta[50] == .(es2[i])),
               x = bquote("\u03B2"[49]),
               y = "Power",
               color = "", shape = "", linetype = "") +
          mytheme #+
         #scale_y_continuous(limits = c(0, 0.6))
         
}

fig1_panels <- ggarrange(plotlist = plots, ncol = 4, nrow = 1, labels = c("A", "B", "C", "D"))
```

<!--## MAF=0.05, linear, other effect size=0.1-->

```{r fig5_0.1,echo=FALSE}
df <- df5[df5$es_other == 0.1,]

# power1 <- cbind(df[,c(2,3,5)],rep("Analytic,True",16))
# power2 <- cbind(df[,c(2,3,6)],rep("Analytic,Mis",16))
power3 <- cbind(df[,c(3,4,5)],rep("Sim,True",16))
power4 <- cbind(df[,c(3,4,6)],rep("Sim,Mis",16))

# colnames(power1)[3:4]<-c("power","group")
# colnames(power2)[3:4]<-c("power","group")
colnames(power3)[3:4]<-c("power","group")
colnames(power4)[3:4]<-c("power","group")

dfnew<-rbind(power3,power4)
dfsub<-list()
line_types <- c(  "dashed", "dashed")

plots <- list()

for (i in 1:4){
  dfsub[[i]] <- dfnew[dfnew$es2==es2[i], ]
  plots[[i]] <- ggplot(dfsub[[i]], aes(x = es1, y = power, group=group)) +
          geom_point(aes(color=group,shape=group)) +
          geom_line(aes(color=group,linetype=group)) +
          scale_linetype_manual(values = line_types) +
          labs(title = bquote(beta[50] == .(es2[i])),
               x = bquote("\u03B2"[49]),
               y = "Power",
               color = "", shape = "", linetype = "") +
          mytheme #+
         #scale_y_continuous(limits = c(0, 0.6))
         
}

fig2_panels <- ggarrange(plotlist = plots, ncol = 4, nrow = 1, labels = c("E", "F", "G", "H"))
```

<!--## MAF=0.05, linear, other effect size=0.2-->

```{r fig5_0.2,echo=FALSE,eval=FALSE}
df <- df5[df5$es_other == 0.2,]
# power1 <- cbind(df[,c(2,3,5)],rep("Analytic,True",16))
# power2 <- cbind(df[,c(2,3,6)],rep("Analytic,Mis",16))
power3 <- cbind(df[,c(3,4,5)],rep("Sim,True",16))
power4 <- cbind(df[,c(3,4,6)],rep("Sim,Mis",16))

# colnames(power1)[3:4]<-c("power","group")
# colnames(power2)[3:4]<-c("power","group")
colnames(power3)[3:4]<-c("power","group")
colnames(power4)[3:4]<-c("power","group")

dfnew<-rbind(power3,power4)
dfsub<-list()
line_types <- c(  "dashed", "dashed")
plots <- list()
for (i in 1:4){
  dfsub[[i]] <- dfnew[dfnew$es2==es2[i], ]
  plots[[i]] <- ggplot(dfsub[[i]], aes(x = es1, y = power, group=group)) +
          geom_point(aes(color=group,shape=group)) +
          geom_line(aes(color=group,linetype=group)) +
          scale_linetype_manual(values = line_types) +
          labs(title = bquote(beta[50] == .(es2[i])),
               x = bquote("\u03B2"[49]),
               y = "Power",
               color = "", shape = "", linetype = "") +
          mytheme #+
         #scale_y_continuous(limits = c(0, 0.6))
         
}

fig3_panels <- ggarrange(plotlist = plots, ncol = 4, nrow = 1, labels = c("I", "J", "K", "L"))

```

<!--## MAF=0.2, linear, other effect size=0-->

```{r fig6_0,echo=FALSE}
df <- df6[df6$es_other == 0,]
# power1 <- cbind(df[,c(2,3,5)],rep("Analytic,True",16))
# power2 <- cbind(df[,c(2,3,6)],rep("Analytic,Mis",16))
power3 <- cbind(df[,c(3,4,5)],rep("Sim,True",16))
power4 <- cbind(df[,c(3,4,6)],rep("Sim,Mis",16))

# colnames(power1)[3:4]<-c("power","group")
# colnames(power2)[3:4]<-c("power","group")
colnames(power3)[3:4]<-c("power","group")
colnames(power4)[3:4]<-c("power","group")

dfnew<-rbind(power3,power4)
dfsub<-list()
line_types <- c(  "dashed", "dashed")
plots <- list()
for (i in 1:4){
  dfsub[[i]] <- dfnew[dfnew$es2==es2[i], ]
  plots[[i]] <- ggplot(dfsub[[i]], aes(x = es1, y = power, group=group)) +
          geom_point(aes(color=group,shape=group)) +
          geom_line(aes(color=group,linetype=group)) +
          scale_linetype_manual(values = line_types) +
          labs(title = bquote(beta[50] == .(es2[i])),
               x = bquote("\u03B2"[49]),
               y = "Power",
               color = "", shape = "", linetype = "") +
          mytheme #+
         #scale_y_continuous(limits = c(0, 0.6))
         
}

fig4_panels <- ggarrange(plotlist = plots, ncol = 4, nrow = 1, labels = c("A", "B", "C", "D"))
```

<!--## MAF=0.2, linear, other effect size=0.1-->

```{r fig6_0.1,echo=FALSE}
df <- df6[df6$es_other == 0.1,]
# power1 <- cbind(df[,c(2,3,5)],rep("Analytic,True",16))
# power2 <- cbind(df[,c(2,3,6)],rep("Analytic,Mis",16))
power3 <- cbind(df[,c(3,4,5)],rep("Sim,True",16))
power4 <- cbind(df[,c(3,4,6)],rep("Sim,Mis",16))

# colnames(power1)[3:4]<-c("power","group")
# colnames(power2)[3:4]<-c("power","group")
colnames(power3)[3:4]<-c("power","group")
colnames(power4)[3:4]<-c("power","group")

dfnew<-rbind(power3,power4)
dfsub<-list()
line_types <- c(  "dashed", "dashed")
plots <- list()
for (i in 1:4){
  dfsub[[i]] <- dfnew[dfnew$es2==es2[i], ]
  plots[[i]] <- ggplot(dfsub[[i]], aes(x = es1, y = power, group=group)) +
          geom_point(aes(color=group,shape=group)) +
          geom_line(aes(color=group,linetype=group)) +
          scale_linetype_manual(values = line_types) +
          labs(title = bquote(beta[50] == .(es2[i])),
               x = bquote("\u03B2"[49]),
               y = "Power",
               color = "", shape = "", linetype = "") +
          mytheme #+
         #scale_y_continuous(limits = c(0, 0.6))
         
}

fig5_panels <- ggarrange(plotlist = plots, ncol = 4, nrow = 1, labels = c("E", "F", "G", "H"))
```

<!--## MAF=0.2, linear, other effect size=0.2-->

```{r fig6_0.2,echo=FALSE,eval=FALSE}
df <- df6[df6$es_other == 0.2,]
# power1 <- cbind(df[,c(2,3,5)],rep("Analytic,True",16))
# power2 <- cbind(df[,c(2,3,6)],rep("Analytic,Mis",16))
power3 <- cbind(df[,c(3,4,5)],rep("Sim,True",16))
power4 <- cbind(df[,c(3,4,6)],rep("Sim,Mis",16))

# colnames(power1)[3:4]<-c("power","group")
# colnames(power2)[3:4]<-c("power","group")
colnames(power3)[3:4]<-c("power","group")
colnames(power4)[3:4]<-c("power","group")

dfnew<-rbind(power3,power4)
dfsub<-list()
line_types <- c(  "dashed", "dashed")

plots <- list()
for (i in 1:4){
  dfsub[[i]] <- dfnew[dfnew$es2==es2[i], ]
  plots[[i]] <- ggplot(dfsub[[i]], aes(x = es1, y = power, group=group)) +
          geom_point(aes(color=group,shape=group)) +
          geom_line(aes(color=group,linetype=group)) +
          scale_linetype_manual(values = line_types) +
          labs(title = bquote(beta[50] == .(es2[i])),
               x = bquote("\u03B2"[49]),
               y = "Power",
               color = "", shape = "", linetype = "") +
          mytheme #+
         #scale_y_continuous(limits = c(0, 0.6))
         
}

fig6_panels <- ggarrange(plotlist = plots, ncol = 4, nrow = 1, labels = c("I", "J", "K", "L"))

```


## MAF=0.05,  other effect size=0/0.1

```{r combine1_linear,echo=FALSE, cache=FALSE, warning=FALSE}
# Create a dummy plot using data from any of the chunks (e.g., dfnew1)
# to extract the legend
dummy_plot <- ggplot(dfnew, aes(x = es1, y = power,
                                color = group,
                                linetype = group,
                                shape = group)) +
  geom_point() +
  geom_line() +
  scale_linetype_manual(values = c("dashed", "dashed")) +
  theme(legend.position = "bottom") +
  labs(color = NULL, linetype = NULL, shape = NULL) # Remove legend titles

# Extract the legend
legend <- cowplot::get_legend(dummy_plot)

# --- Create Final Figure 1 (Combining original Fig 1 & 2) ---
# Arrange the panels of fig1 and fig2 vertically
combined_fig_1 <- ggarrange(
  fig1_panels, fig2_panels, #fig3_panels,
  nrow = 2, ncol = 1
  # No common legend here, add it below
)


# Add the shared legend to the bottom
final_plot_1 <- ggarrange(
  combined_fig_1, legend,
  nrow = 2, ncol = 1,
  heights = c(10, 1) # Adjust ratio for plot vs legend as needed
)


# Print the first final figure
print(final_plot_1)

```

## MAF=0.2,  other effect size=0/0.1

```{r combine2_linear,echo=FALSE, cache=FALSE, warning=FALSE}


combined_fig_2 <- ggarrange(
  fig4_panels, fig5_panels, #fig6_panels, 
  nrow = 2, ncol = 1
  # No common legend here, add it below
)


# Add the shared legend to the bottom

final_plot_2 <- ggarrange(
  combined_fig_2, legend,
  nrow = 2, ncol = 1,
  heights = c(10, 1) # Adjust ratio for plot vs legend as needed
)

# Print the first final figure
print(final_plot_2)


```
