#BSUB -J realCwT0.05[1-48]
#BSUB -W 3:00
#BSUB -o /rsrch6/home/biostatistics/nkui/simu/ck.out
#BSUB -e /rsrch6/home/biostatistics/nkui/simu/ck.err
#BSUB -cwd /rsrch6/home/biostatistics/nkui/simu/
#BSUB -q short
#BSUB -u nkui@mdanderson.org
#BSUB -n 1
#BSUB -M 10
#BSUB -R rusage[mem=10]
#BSUB -B
#BSUB -N
module load R/4.4
echo "${LSB_JOBINDEX}"
echo $HOSTNAME
Rscript  realCwT0.05.R  ${LSB_JOBINDEX}
